Project4: main.o btree.o stack.o
	gcc -o Project4 main.o btree.o stack.o

main.o: main.c header.h
	gcc -c main.c

btree.o: btree.c header.h
	gcc -c btree.c

stack.o: stack.c header.h
	gcc -c stack.c