Project5: main.o stack.o token.o
	g++ -o Project5 main.o stack.o token.o

main.o: main.cpp header.h
	g++ -c main.cpp

stack.o: stack.cpp header.h
	g++ -c stack.cpp

token.o: token.cpp header.h
	g++ -c token.cpp